server:
  port: 3000

db:
  type: 'postgress'
  host: 'localhost'
  port: 5432
  username: ''
  password: ''
  database: 'nest-study'
  synchronize: true

jwt:
  expiresIn: 3000
  secretKey: 'nest-stduy'
